source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ios-UITest' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'JSONModel'
pod 'PNChart'
pod 'ZYQAssetPickerController',  '~> 1.0.0'
pod 'UICountingLabel'
pod 'FreeStreamer'
pod 'Mantle'
pod 'PYSearch'
pod 'AMap3DMap' #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使用)
pod 'AMapSearch' #搜索功能
pod 'ReactiveObjC'
end

